"""Tests for the `provenex audit` CLI subcommand.

The audit command is the auditor's tool: given a receipt JSON, validate
the signature (if a secret is in the environment) and verify every
inclusion proof against the receipt's transparency-log tree root.
Needs no database access.
"""

from __future__ import annotations

import io
import json
import tempfile
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from typing import Tuple

import pytest

from provenex.cli.main import main
from provenex.core.fingerprinter import Fingerprinter
from provenex.core.receipt import HmacSha256Signer, ReceiptBuilder
from provenex.index.merkle_sqlite_index import MerkleSQLiteProvenanceIndex
from provenex.policy.policy import VerificationPolicy


_DEMO_TEXT = (
    "Encryption policy. All data at rest must be encrypted using AES-256-GCM "
    "with keys generated by the enterprise KMS. Key-encryption keys must be "
    "rotated quarterly. "
) * 3


def _write_receipt(workdir: Path) -> Tuple[Path, str]:
    """Build a real Merkle-backed receipt and return (path, fingerprint)."""
    index = MerkleSQLiteProvenanceIndex(str(workdir / "p.db"))
    fp = Fingerprinter()
    result = fp.fingerprint(_DEMO_TEXT)
    for f in result.fingerprints:
        index.add(
            fingerprint=f.fingerprint,
            document_id="policy_v1",
            document_version=result.document_version,
            chunk_offset=f.offset,
            chunk_length=f.length,
            authorized=True,
        )
    target_fp = result.fingerprints[0].fingerprint
    leaf_bytes, leaf_index, proof = index.inclusion_proof(target_fp)
    builder = ReceiptBuilder(policy=VerificationPolicy())
    builder.add_source(
        fingerprint=target_fp,
        outcome=index.verify(target_fp),
        entry=index.lookup(target_fp),
        leaf_index=leaf_index,
        inclusion_proof=proof,
    )
    receipt = builder.finalize(
        output_text="model answer",
        signer=HmacSha256Signer(),
        transparency_log={
            "tree_size": index.tree_size(),
            "tree_root": index.tree_root(),
        },
    )
    out = workdir / "receipt.json"
    out.write_text(receipt.to_json())
    index.close()
    return out, target_fp


def _run_audit(*argv: str) -> Tuple[int, str, str]:
    """Invoke `provenex audit <argv>` in-process. Returns (exit, stdout, stderr)."""
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        code = main(["audit", *argv])
    return code, out.getvalue(), err.getvalue()


def test_audit_valid_receipt_returns_zero(monkeypatch, tmp_path=None):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 0
    assert "PASS" in stdout
    assert "INVALID" not in stdout


def test_audit_tampered_receipt_returns_nonzero(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    # Modify the receipt on disk after signing — signature and proof should
    # both fail because the canonical leaf bytes depend on document_id.
    data = json.loads(receipt_path.read_text())
    data["sources"][0]["document_id"] = "FORGED"
    receipt_path.write_text(json.dumps(data))
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 1
    assert "FAIL" in stdout
    assert "INVALID" in stdout


def test_audit_without_signing_secret_fails_without_unsigned_flag(monkeypatch):
    """No env secret + no --public-key + no --unsigned should FAIL.

    Refusing to verify is safer than silently passing an unverifiable receipt.
    """
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    monkeypatch.delenv("PROVENEX_SIGNING_SECRET")
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 1
    assert "no key material" in stdout.lower() or "--unsigned" in stdout


def test_audit_without_signing_secret_passes_with_unsigned_flag(monkeypatch):
    """With --unsigned, the missing-key case is acknowledged and overall PASS."""
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    monkeypatch.delenv("PROVENEX_SIGNING_SECRET")
    code, stdout, _ = _run_audit("--unsigned", str(receipt_path))
    assert code == 0
    assert "skipped" in stdout.lower() or "unsigned" in stdout.lower()
    assert "PASS" in stdout


def test_audit_json_output_has_required_keys(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    code, stdout, _ = _run_audit("--json", str(receipt_path))
    assert code == 0
    report = json.loads(stdout)
    assert report["overall"] == "PASS"
    assert report["signature"]["ok"] is True
    assert report["receipt_id"].startswith("prx_")
    assert report["schema_version"] == "2.3.0"
    assert len(report["inclusion_proofs"]) == 1
    assert report["inclusion_proofs"][0]["ok"] is True


def test_audit_quiet_emits_only_pass_or_fail(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    code, stdout, _ = _run_audit("--quiet", str(receipt_path))
    assert code == 0
    assert stdout.strip() == "PASS"


def test_audit_invalid_json_returns_two():
    bad = Path(tempfile.mktemp(suffix=".json"))
    bad.write_text("not valid json")
    code, _, stderr = _run_audit(str(bad))
    assert code == 2
    assert "not valid JSON" in stderr


# --------------------------------------------------------------------------- #
# Trajectory audit (--trajectory mode, RFC-0003)                              #
# --------------------------------------------------------------------------- #


def _write_trajectory_chain(workdir: Path, n: int) -> list[Path]:
    """Write n linearly-chained, signed, Merkle-backed receipts to disk."""
    from provenex.core.trajectory import start_trajectory

    index = MerkleSQLiteProvenanceIndex(str(workdir / "p.db"))
    fp = Fingerprinter()
    result = fp.fingerprint(_DEMO_TEXT)
    for f in result.fingerprints:
        index.add(
            fingerprint=f.fingerprint,
            document_id="policy_v1",
            document_version=result.document_version,
            chunk_offset=f.offset,
            chunk_length=f.length,
            authorized=True,
        )
    target_fp = result.fingerprints[0].fingerprint
    leaf_bytes, leaf_index, proof = index.inclusion_proof(target_fp)
    signer = HmacSha256Signer()

    paths: list[Path] = []
    traj = start_trajectory(agent_id="test_agent")
    last_receipt = None
    for i in range(n):
        if last_receipt is not None:
            traj = traj.next_step(parent_receipts=[last_receipt])
        b = ReceiptBuilder(policy=VerificationPolicy())
        b.add_source(
            fingerprint=target_fp,
            outcome=index.verify(target_fp),
            entry=index.lookup(target_fp),
            leaf_index=leaf_index,
            inclusion_proof=proof,
        )
        r = b.finalize(
            output_text=f"step {i}",
            signer=signer,
            transparency_log={
                "tree_size": index.tree_size(),
                "tree_root": index.tree_root(),
            },
            trajectory=traj,
        )
        path = workdir / f"step_{i:03d}.json"
        path.write_text(r.to_json())
        paths.append(path)
        last_receipt = r
    index.close()
    return paths


def test_audit_trajectory_passes_on_valid_chain(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    _write_trajectory_chain(workdir, n=3)
    code, stdout, _ = _run_audit("--trajectory", str(workdir))
    assert code == 0
    assert "PASS" in stdout
    assert "FAIL" not in stdout


def test_audit_trajectory_accepts_glob(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    _write_trajectory_chain(workdir, n=2)
    code, stdout, _ = _run_audit(
        "--trajectory", str(workdir / "step_*.json")
    )
    assert code == 0
    assert "PASS" in stdout


def test_audit_trajectory_fails_on_mixed_trajectory_ids(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    # Two separate trajectories of two steps each, all in the same directory.
    _write_trajectory_chain(workdir, n=2)
    workdir2 = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    second = _write_trajectory_chain(workdir2, n=2)
    # Move the second trajectory's receipts into the first directory.
    for src in second:
        dest = workdir / ("other_" + src.name)
        dest.write_text(src.read_text())
    code, stdout, _ = _run_audit("--trajectory", str(workdir))
    assert code == 1
    assert "FAIL" in stdout
    assert "shared_trajectory_id" in stdout


def test_audit_trajectory_fails_on_tampered_receipt(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    paths = _write_trajectory_chain(workdir, n=3)
    # Tamper with one receipt's trajectory.step_index — signature must fail.
    data = json.loads(paths[1].read_text())
    data["trajectory"]["step_index"] = 99
    paths[1].write_text(json.dumps(data))
    code, stdout, _ = _run_audit("--trajectory", str(workdir))
    assert code == 1
    assert "FAIL" in stdout


def test_audit_trajectory_json_output(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    _write_trajectory_chain(workdir, n=3)
    code, stdout, _ = _run_audit("--trajectory", str(workdir), "--json")
    assert code == 0
    report = json.loads(stdout)
    assert report["overall"] == "PASS"
    assert report["trajectory_id"].startswith("trj_")
    assert report["receipt_count"] == 3
    assert len(report["receipts"]) == 3
    # Every per-receipt entry has the expected shape.
    for r in report["receipts"]:
        assert r["ok"] is True
        assert r["receipt_id"].startswith("prx_")
        assert r["step_index"] in {0, 1, 2}
    # DAG checks are listed.
    check_names = {c["name"] for c in report["trajectory_checks"]}
    assert "has_trajectory_block" in check_names
    assert "shared_trajectory_id" in check_names
    assert "dag_acyclic" in check_names
    assert "has_root_step" in check_names
    assert "no_dangling_parents" in check_names


def test_audit_trajectory_quiet_emits_only_pass(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    _write_trajectory_chain(workdir, n=2)
    code, stdout, _ = _run_audit("--trajectory", str(workdir), "--quiet")
    assert code == 0
    assert stdout.strip() == "PASS"


def test_audit_trajectory_empty_directory_returns_two():
    empty = Path(tempfile.mkdtemp())
    code, _, stderr = _run_audit("--trajectory", str(empty))
    assert code == 2
    assert "no receipt files" in stderr.lower()


def test_audit_trajectory_mutually_exclusive_with_positional(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    code, _, stderr = _run_audit(
        "--trajectory", str(workdir), str(receipt_path)
    )
    assert code == 2
    assert "mutually exclusive" in stderr


def test_audit_with_no_arguments_returns_two():
    code, _, stderr = _run_audit()
    # argparse may handle the missing-required-arg internally with exit 2
    # before we reach our error message. Either way, exit code 2.
    assert code == 2


def test_audit_trajectory_fails_when_one_signature_breaks(monkeypatch):
    """Per-receipt audit catches a broken signature even if the DAG is valid."""
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    paths = _write_trajectory_chain(workdir, n=2)
    # Forge the signature on receipt[0].
    data = json.loads(paths[0].read_text())
    data["signature"]["value"] = "00" * 32
    paths[0].write_text(json.dumps(data))
    code, stdout, _ = _run_audit("--trajectory", str(workdir))
    assert code == 1
    assert "FAIL" in stdout


def test_audit_receipt_without_transparency_log_still_works(monkeypatch):
    """A 1.0.0 receipt (no transparency_log, no inclusion proofs) should
    succeed on signature check alone and report 'no inclusion proofs'."""
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    data = json.loads(receipt_path.read_text())
    # Strip the Merkle bits to emulate an old-style receipt.
    data.pop("transparency_log", None)
    for s in data["sources"]:
        s.pop("leaf_index", None)
        s.pop("inclusion_proof", None)
    # Re-sign so the signature matches the stripped-down body.
    data.pop("signature", None)
    payload = json.dumps(data, sort_keys=True, separators=(",", ":")).encode("utf-8")
    data["signature"] = {
        "algorithm": "hmac-sha256",
        "value": HmacSha256Signer().sign(payload),
    }
    receipt_path.write_text(json.dumps(data))
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 0
    assert "No inclusion proofs" in stdout
