"""Tests for the `provenex audit` CLI subcommand.

The audit command is the auditor's tool: given a receipt JSON, validate
the signature (if a secret is in the environment) and verify every
inclusion proof against the receipt's transparency-log tree root.
Needs no database access.
"""

from __future__ import annotations

import io
import json
import tempfile
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from typing import Tuple

import pytest

from provenex.cli.main import main
from provenex.core.fingerprinter import Fingerprinter
from provenex.core.receipt import HmacSha256Signer, ReceiptBuilder
from provenex.index.merkle_sqlite_index import MerkleSQLiteProvenanceIndex
from provenex.policy.policy import VerificationPolicy


_DEMO_TEXT = (
    "Encryption policy. All data at rest must be encrypted using AES-256-GCM "
    "with keys generated by the enterprise KMS. Key-encryption keys must be "
    "rotated quarterly. "
) * 3


def _write_receipt(workdir: Path) -> Tuple[Path, str]:
    """Build a real Merkle-backed receipt and return (path, fingerprint)."""
    index = MerkleSQLiteProvenanceIndex(str(workdir / "p.db"))
    fp = Fingerprinter()
    result = fp.fingerprint(_DEMO_TEXT)
    for f in result.fingerprints:
        index.add(
            fingerprint=f.fingerprint,
            document_id="policy_v1",
            document_version=result.document_version,
            chunk_offset=f.offset,
            chunk_length=f.length,
            authorized=True,
        )
    target_fp = result.fingerprints[0].fingerprint
    leaf_bytes, leaf_index, proof = index.inclusion_proof(target_fp)
    builder = ReceiptBuilder(policy=VerificationPolicy())
    builder.add_source(
        fingerprint=target_fp,
        outcome=index.verify(target_fp),
        entry=index.lookup(target_fp),
        leaf_index=leaf_index,
        inclusion_proof=proof,
    )
    receipt = builder.finalize(
        output_text="model answer",
        signer=HmacSha256Signer(),
        transparency_log={
            "tree_size": index.tree_size(),
            "tree_root": index.tree_root(),
        },
    )
    out = workdir / "receipt.json"
    out.write_text(receipt.to_json())
    index.close()
    return out, target_fp


def _run_audit(*argv: str) -> Tuple[int, str, str]:
    """Invoke `provenex audit <argv>` in-process. Returns (exit, stdout, stderr)."""
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        code = main(["audit", *argv])
    return code, out.getvalue(), err.getvalue()


def test_audit_valid_receipt_returns_zero(monkeypatch, tmp_path=None):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 0
    assert "PASS" in stdout
    assert "INVALID" not in stdout


def test_audit_tampered_receipt_returns_nonzero(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    # Modify the receipt on disk after signing — signature and proof should
    # both fail because the canonical leaf bytes depend on document_id.
    data = json.loads(receipt_path.read_text())
    data["sources"][0]["document_id"] = "FORGED"
    receipt_path.write_text(json.dumps(data))
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 1
    assert "FAIL" in stdout
    assert "INVALID" in stdout


def test_audit_without_signing_secret_skips_signature(monkeypatch):
    """No env secret should mean signature check is skipped (still proves the
    inclusion proof). Overall result still PASS for an untampered receipt."""
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    monkeypatch.delenv("PROVENEX_SIGNING_SECRET")
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 0
    assert "skipped" in stdout.lower()
    assert "PASS" in stdout


def test_audit_json_output_has_required_keys(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    code, stdout, _ = _run_audit("--json", str(receipt_path))
    assert code == 0
    report = json.loads(stdout)
    assert report["overall"] == "PASS"
    assert report["signature"]["ok"] is True
    assert report["receipt_id"].startswith("prx_")
    assert report["schema_version"] == "1.1.0"
    assert len(report["inclusion_proofs"]) == 1
    assert report["inclusion_proofs"][0]["ok"] is True


def test_audit_quiet_emits_only_pass_or_fail(monkeypatch):
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    code, stdout, _ = _run_audit("--quiet", str(receipt_path))
    assert code == 0
    assert stdout.strip() == "PASS"


def test_audit_invalid_json_returns_two():
    bad = Path(tempfile.mktemp(suffix=".json"))
    bad.write_text("not valid json")
    code, _, stderr = _run_audit(str(bad))
    assert code == 2
    assert "not valid JSON" in stderr


def test_audit_receipt_without_transparency_log_still_works(monkeypatch):
    """A 1.0.0 receipt (no transparency_log, no inclusion proofs) should
    succeed on signature check alone and report 'no inclusion proofs'."""
    workdir = Path(tempfile.mkdtemp())
    monkeypatch.setenv("PROVENEX_SIGNING_SECRET", "test_secret_for_audit_v1")
    receipt_path, _ = _write_receipt(workdir)
    data = json.loads(receipt_path.read_text())
    # Strip the Merkle bits to emulate an old-style receipt.
    data.pop("transparency_log", None)
    for s in data["sources"]:
        s.pop("leaf_index", None)
        s.pop("inclusion_proof", None)
    # Re-sign so the signature matches the stripped-down body.
    data.pop("signature", None)
    payload = json.dumps(data, sort_keys=True, separators=(",", ":")).encode("utf-8")
    data["signature"] = {
        "algorithm": "hmac-sha256",
        "value": HmacSha256Signer().sign(payload),
    }
    receipt_path.write_text(json.dumps(data))
    code, stdout, _ = _run_audit(str(receipt_path))
    assert code == 0
    assert "No inclusion proofs" in stdout
