"""End-to-end Provenex demo. Pure stdlib, no LangChain.

Run with::

    PROVENEX_SIGNING_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')" \
        python examples/standalone_demo.py

What it shows, in order:

    1. Ingest a small document into a Merkle-backed provenance index.
       Print the resulting tree root (the public audit anchor).

    2. Verify a known chunk → VERIFIED. Pull its inclusion proof out
       of the index. A ~log2(N) audit path.

    3. Tamper with one row of the underlying SQLite database. Re-run
       verify; the HMAC layer catches it (outcome: TAMPERED).

    4. Audit offline. Pretend the database is gone. Using only the
       receipt JSON and the previously-published tree root, verify
       the inclusion proof. This is the load-bearing demo moment:
       the proof is verifiable forever, against any future tree-root
       publication, with no access to the original index.

Total runtime ~12 s with default pacing. Pass ``--fast`` to skip the
sleeps if you're not recording. Designed to be recorded with
``asciinema rec demo.cast -c 'python examples/standalone_demo.py'``.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
import tempfile
import time
from pathlib import Path

from provenex.core.fingerprinter import Fingerprinter
from provenex.core.merkle import verify_inclusion_proof
from provenex.core.receipt import HmacSha256Signer, ReceiptBuilder
from provenex.index.merkle_sqlite_index import MerkleSQLiteProvenanceIndex
from provenex.policy.policy import VerificationPolicy

# ANSI colors. Disabled
# automatically when stdout is not a TTY (e.g., piped to a file).
_TTY = sys.stdout.isatty()
BOLD = "\033[1m" if _TTY else ""
DIM = "\033[2m" if _TTY else ""
GREEN = "\033[32m" if _TTY else ""
RED = "\033[31m" if _TTY else ""
YELLOW = "\033[33m" if _TTY else ""
CYAN = "\033[36m" if _TTY else ""
RESET = "\033[0m" if _TTY else ""


def banner(title: str) -> None:
    """Print a visually-distinct section header."""
    print()
    print(f"{BOLD}{CYAN}━━━ {title} {'━' * max(0, 60 - len(title))}{RESET}")


def kv(label: str, value: str, color: str = "") -> None:
    print(f"  {DIM}{label:>14}:{RESET} {color}{value}{RESET}")


def pause(seconds: float, *, skip: bool) -> None:
    if not skip:
        time.sleep(seconds)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fast", action="store_true", help="Skip pacing sleeps (CI mode)."
    )
    args = parser.parse_args()

    if not os.environ.get("PROVENEX_SIGNING_SECRET"):
        print(
            f"{RED}error:{RESET} set PROVENEX_SIGNING_SECRET first, e.g.:\n"
            f"  export PROVENEX_SIGNING_SECRET="
            f'"$(python3 -c \'import secrets; print(secrets.token_hex(32))\')"',
            file=sys.stderr,
        )
        return 2

    # Use a fresh temp DB so re-runs are clean and don't pollute cwd.
    workdir = Path(tempfile.mkdtemp(prefix="provenex_demo_"))
    db_path = workdir / "provenance.db"

    # ----------------------------------------------------------------- act 1
    banner("1. Ingest into a Merkle-backed provenance index")

    # Realistic-ish policy doc, sized to produce ~30 sliding-window
    # fingerprints with the default Fingerprinter config (window 128,
    # stride 64). That gives a 5-hash inclusion proof: enough to make the
    # logarithmic shape visible without spamming the terminal.
    document_text = (
        "Encryption policy. All data at rest must be encrypted using AES-256-GCM "
        "with keys generated by the enterprise KMS. Key-encryption keys must be "
        "rotated quarterly; data-encryption keys are rotated on access. Access to "
        "the KMS is restricted to the security engineering team and audited "
        "monthly by an independent reviewer. "
        "Network traffic between services must use TLS 1.3 with forward secrecy. "
        "Self-signed certificates are not permitted in production. Certificate "
        "pinning is required for all third-party integrations. "
        "Backups are encrypted with a separate key hierarchy and stored in a "
        "geographically distinct region. Restore procedures must be drilled "
        "quarterly with verification that the decrypted backup matches the "
        "source-of-truth hash recorded at backup time. "
        "Any deviation from this policy requires sign-off from the CISO and "
        "is recorded in the security exceptions register, reviewed at each "
        "quarterly governance meeting."
    )
    print(f"  {DIM}document:{RESET} policy_v4 ({len(document_text)} chars)")
    pause(0.8, skip=args.fast)

    index = MerkleSQLiteProvenanceIndex(str(db_path))
    fp = Fingerprinter()
    ingest_result = fp.fingerprint(document_text)
    for f in ingest_result.fingerprints:
        index.add(
            fingerprint=f.fingerprint,
            document_id="policy_v4",
            document_version=ingest_result.document_version,
            chunk_offset=f.offset,
            chunk_length=f.length,
            authorized=True,
        )

    print(f"  {GREEN}✓ ingested{RESET} {len(ingest_result.fingerprints)} chunks")
    kv("tree size", str(index.tree_size()))
    kv("tree root", index.tree_root(), color=YELLOW)
    print(
        f"  {DIM}↑ this is the public audit anchor. Publish it, sign it, "
        f"gossip it.{RESET}"
    )
    pause(1.5, skip=args.fast)

    # ----------------------------------------------------------------- act 2
    banner("2. Verify a known chunk + pull its inclusion proof")

    # Pretend a retriever returned the first ~120 chars of the document.
    retrieved_chunk = document_text[: ingest_result.fingerprints[0].length]
    chunk_fp = fp.fingerprint_chunk(retrieved_chunk)
    outcome = index.verify(chunk_fp)
    entry = index.lookup(chunk_fp)

    kv("chunk fp", chunk_fp[:32] + "...")
    kv("outcome", outcome.value, color=GREEN if outcome.value == "VERIFIED" else RED)
    pause(0.6, skip=args.fast)

    leaf_bytes, leaf_index, proof = index.inclusion_proof(chunk_fp)
    kv("leaf index", str(leaf_index))
    kv("proof size", f"{len(proof)} hashes")
    print(f"  {DIM}↑ inclusion proof is ~log2(tree size). Constant-ish.{RESET}")
    pause(1.0, skip=args.fast)

    # Bundle into a signed receipt. This is what the application keeps.
    builder = ReceiptBuilder(policy=VerificationPolicy())
    builder.add_source(
        fingerprint=chunk_fp,
        outcome=outcome,
        entry=entry,
        leaf_index=leaf_index,
        inclusion_proof=proof,
    )
    receipt = builder.finalize(
        output_text="model answer: AES-256, rotated quarterly.",
        signer=HmacSha256Signer(),
        transparency_log={
            "tree_size": index.tree_size(),
            "tree_root": index.tree_root(),
        },
    )
    # Save the receipt to a known path so users can chain `provenex audit`
    # afterwards. The whole point of the next acts is that the receipt is
    # self-contained, so keeping it on disk past the DB deletion is the
    # honest demonstration.
    receipt_path = Path.cwd() / "provenex_demo_receipt.json"
    receipt_path.write_text(receipt.to_json())
    kv("receipt id", receipt.receipt_id, color=CYAN)
    kv("saved to", str(receipt_path))
    print(f"  {GREEN}✓ signed receipt issued{RESET} "
          f"(schema {receipt.schema_version})")
    pause(1.0, skip=args.fast)

    # Stash these values. Act 4 will use them with no database access.
    saved_tree_root = index.tree_root()
    saved_tree_size = index.tree_size()
    saved_leaf_bytes = leaf_bytes
    saved_leaf_index = leaf_index
    saved_proof_hex = list(proof)

    # ----------------------------------------------------------------- act 3
    banner("3. Tamper with the index: HMAC catches it")

    index.close()  # release the write lock so we can edit directly

    # Reach past the API and rewrite a column on disk. This is what a
    # malicious operator with database access (but no signing key) would
    # try. The HMAC over the row payload should refuse to verify.
    # We change chunk_offset rather than document_id so the FK to the
    # documents table stays valid. The failure we want to see is HMAC
    # failure, not a foreign-key constraint error.
    raw = sqlite3.connect(db_path)
    raw.execute(
        "UPDATE fingerprints SET chunk_offset = 999 WHERE fingerprint = ?",
        (chunk_fp,),
    )
    raw.commit()
    raw.close()
    print(f"  {YELLOW}✎ rewrote chunk_offset 0 → 999 directly on disk{RESET}")
    pause(1.0, skip=args.fast)

    reopened = MerkleSQLiteProvenanceIndex(str(db_path))
    tampered_outcome = reopened.verify(chunk_fp)
    kv(
        "outcome",
        tampered_outcome.value,
        color=RED if tampered_outcome.value == "TAMPERED" else YELLOW,
    )
    print(
        f"  {DIM}↑ HMAC signature over the row payload failed. The "
        f"signing key wasn't compromised; only the bytes on disk were.{RESET}"
    )
    reopened.close()
    pause(1.5, skip=args.fast)

    # ----------------------------------------------------------------- act 4
    banner("4. Offline audit: verify with no database access")

    # Throw the database away. An auditor opening the receipt five years
    # from now has none of this on hand. Only the receipt JSON and the
    # tree root that was published at the time.
    db_path.unlink()
    print(f"  {DIM}× deleted the SQLite database{RESET}")
    pause(0.6, skip=args.fast)

    proof_bytes = [bytes.fromhex(p.split(":", 1)[1]) for p in saved_proof_hex]
    root_bytes = bytes.fromhex(saved_tree_root.split(":", 1)[1])

    ok = verify_inclusion_proof(
        leaf=saved_leaf_bytes,
        leaf_index=saved_leaf_index,
        tree_size=saved_tree_size,
        proof=proof_bytes,
        root=root_bytes,
    )
    kv(
        "verify result",
        "PROOF VALID" if ok else "PROOF INVALID",
        color=GREEN if ok else RED,
    )
    print(
        f"  {DIM}↑ verified using only: receipt fields + the published "
        f"tree root. No database. No signing key. No network.{RESET}"
    )
    pause(1.5, skip=args.fast)

    # ----------------------------------------------------------------- coda
    banner("Scale (from docs/scaling.md, single-threaded i7-8750H)")
    print(f"  {DIM}corpus:{RESET}  1,000,000 chunks, 987 MB on disk")
    print(f"  {DIM}ingest:{RESET}  12.2 min  ({GREEN}1,400 chunks/sec{RESET})")
    print(f"  {DIM}verify:{RESET}  p50 {GREEN}371 µs{RESET}  /  p99 599 µs")
    print(f"  {DIM}proof:{RESET}   p50 {GREEN}403 µs{RESET} gen, {GREEN}47 µs{RESET} offline verify")
    print(f"  {DIM}size:{RESET}    20-hash inclusion proofs (≈ log₂(1M))")
    print()
    print(f"  {BOLD}Reproduce:{RESET} python -m bench.scale --scale 1m")
    print()
    print(f"  {BOLD}Re-verify the receipt offline:{RESET}")
    print(f"    provenex audit {receipt_path.name}")
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
